### PR TITLE
new scene (waterfall)

### PR DESCRIPTION
**Pull request by radicalTailor**

### CODE REVIEW

**Comment by ewanhowell5195** [comment]
Could you change the waterfall to be 1 long cuboid, rather than 4 individual cubes. This will help solve the translucency bugs caused by the semi transparent texture

**Comment by ewanhowell5195** [comment]
and also set the north face of the inner water cube to be transparent

**Comment by ewanhowell5195** [comment]
also also, disable the faces of the inner water cube that touch the dirt, as they are currently z-fighting

**Comment by radicalTailor** [comment]
not sure if this is what you wanted

**Pull request merged**
