### PR TITLE
Added Plains-meadow scene

### PR DESCRIPTION
**Pull request by radicalTailor**
Remix of Minecraft-Overworld scene but with flowers for extra coolness

### CODE REVIEW

**Comment by ewanhowell5195** [comment]
Please delete temp.txt

Your bbscene and image are named incorrectly

**Comment by radicalTailor** [comment]
> Please delete temp.txt
> 
> Your bbscene and image are named incorrectly

temp deleted, but wdym the names are incorrect? should they be the same as the scene id?

**Comment by ewanhowell5195** [comment]
also please fix the scenes.json to remove the blank line and give the added bits consistent indentaion with the rest of the file

**Comment by ewanhowell5195** [comment]
compare your scene files to the other scene files. also it says what to name them in the readme. They should be named `scene.bbscene` and `scene.webp`

**Comment by ewanhowell5195** [comment]
The image needs to be in the `webp` format, not the `png` format

**Comment by radicalTailor** [comment]
should be okay now

**Pull request merged**
